<?php
if (session_status() == PHP_SESSION_NONE) {
    session_start();
}

$idioma = 'es'; // idioma por defecto

if (isset($_COOKIE['idiomaSeleccionado'])) {
    $idioma = $_COOKIE['idiomaSeleccionado'];
}

function traducir($clave, $idioma) {
    $traducciones = [
        'es' => [
            'crear_usuario' => 'Crear usuario',
            'iniciar_sesion' => 'Iniciar sesión',
            'cerrar_sesion' => 'Cerrar sesión',
            'creacion_usuario' => 'Creación de Usuario',
            'correo_electronico' => 'Correo electrónico:',
            'nombre_usuario' => 'Nombre de usuario:',
            'rut' => 'RUT:',
            'contrasena' => 'Contraseña:',
            'volver_inicio' => 'Volver a inicio',
            'entrar' => 'Entrar',
            'Me gustaría recibir notificaciones de nuevos boletines.' => 'Me gustaría recibir notificaciones de nuevos boletines.',
            'Solicitar Boletín' => 'Solicitar boletín',
            'Sesión iniciada como' => 'Sesión iniciada como',
            'Ver Borradores' => 'Ver borradores',
            'Ver Solicitudes' => 'Ver solicitudes',
            'Boletines Disponibles' => 'Boletines disponibles',
            'Borradores Disponibles' => 'Borradores disponibles',
            'Buscar por título o palabra clave...' => 'Buscar por título o palabra clave...',
            'Leer PDF' => 'Leer PDF',
            'Aceptar' => 'Aceptar',
            'Denegar' => 'Denegar',
            'Otras noticias' => 'Otras noticias',
            'Solicitudes pendientes' => 'Solicitudes pendientes',
            'Formulario de Boletín' => 'Formulario de Boletín',
            'Ingrese palabras clave' => 'Ingrese palabras clave', 
            'Cosechas, Sistemas, Ciencia, etc..' => 'Cosechas, Sistemas, Ciencia, etc..',
            'Ingrese una descripción de lo que su empresa busca, objetivos y criterios' => 'Ingrese una descripción de lo que su empresa busca, objetivos y criterios',
            'Describa aquí lo que su empresa busca...' => 'Describa aquí lo que su empresa busca...',
            'Ingrese el rut de su empresa' => 'Ingrese el rut de su empresa', 
            'Enviar' => 'Enviar',
            'SITIOS DE INTERÉS' => 'SITIOS DE INTERÉS',
            'Ministerio de Agricultura' => 'Ministerio de Agricultura',
            'Licitaciones de proveedores' => 'Licitaciones de proveedores',
            'Gobierno Transparente' => 'Gobierno Transparente',
            'Solicitudes de Transparencia' => 'Solicitudes de Transparencia',
            'Memorias FIA' => 'Memorias FIA',
            'Teléfono' => 'Teléfono',
            'REDES SOCIALES' => 'Redes Sociales',
            'FUNDACIÓN PARA LA INNOVACIÓN AGRARIA. Todos los derechos reservados.' => 'FUNDACIÓN PARA LA INNOVACIÓN AGRARIA. Todos los derechos reservados.',
            'CONTACTO' => 'CONTACTO',
            'Con puntos y guión' => 'Con puntos y guión',
        ],
        'en' => [
            'crear_usuario' => 'Sign in',
            'iniciar_sesion' => 'Log in',
            'cerrar_sesion' => 'Log out',
            'creacion_usuario' => 'Create User',
            'correo_electronico' => 'Email:',
            'nombre_usuario' => 'Username:',
            'rut' => 'ID Number:',
            'contrasena' => 'Password:',
            'volver_inicio' => 'Back to home',
            'entrar' => 'Enter',
            'Me gustaría recibir notificaciones de nuevos boletines.' => 'I would like to receive notifications of new newsletters.',
            'Solicitar Boletín' => 'Request newsletter',
            'Sesión iniciada como' => 'Session started as',
            'Ver Borradores' => 'View drafts',
            'Ver Solicitudes' => 'View requests',
            'Boletines Disponibles' => 'Available newsletters',
            'Borradores Disponibles' => 'Available drafts',
            'Buscar por título o palabra clave...' => 'Search by title or keyword...',
            'Leer PDF' => 'Read PDF',
            'Aceptar' => 'Accept',
            'Denegar' => 'Deny',
            'Otras noticias' => 'Other news',
            'Solicitudes pendientes' => 'Pending requests',
            'Formulario de Boletín' => 'Newsletter Form',
            'Ingrese palabras clave' => 'Enter keywords',
            'Cosechas, Sistemas, Ciencia, etc..' => 'Harvests, Systems, Science, etc..',
            'Describa aquí lo que su empresa busca...' => 'Describe here what your company is looking for...',
            'Ingrese una descripción de lo que su empresa busca, objetivos y criterios' => 'Enter a description of what your company is looking for, objectives and criteria',
            'Ingrese el rut de su empresa' => 'Enter your company\'s ID number',
            'Enviar' => 'Send',
            'SITIOS DE INTERÉS' => 'SITES OF INTEREST',
            'Ministerio de Agricultura' => 'Ministry of Agriculture',
            'Licitaciones de proveedores' => 'Supplier tenders',
            'Gobierno Transparente' => 'Transparent Government',
            'Solicitudes de Transparencia' => 'Transparency Requests',
            'Memorias FIA' => 'FIA Reports',
            'Teléfono' => 'Phone',
            'REDES SOCIALES' => 'Social Networks',
            'FUNDACIÓN PARA LA INNOVACIÓN AGRARIA. Todos los derechos reservados.' => 'FOUNDATION FOR AGRICULTURAL INNOVATION. All rights reserved.',
            'CONTACTO' => 'CONTACT',
            'Con puntos y guión' => 'With dots and dash',
        ],
        'fr' => [
            'crear_usuario' => 'Créer un utilisateur',
            'iniciar_sesion' => 'Se connecter',
            'cerrar_sesion' => 'Se déconnecter',
            'creacion_usuario' => 'Création d\'utilisateur',
            'correo_electronico' => 'E-mail:',
            'nombre_usuario' => 'Nom d\'utilisateur:',
            'rut' => 'Numéro d\'identification:',
            'contrasena' => 'Mot de passe:',
            'volver_inicio' => 'Retour à l\'accueil',
            'entrar' => 'Entrer',
            'Me gustaría recibir notificaciones de nuevos boletines.' => 'Je voudrais recevoir des notifications de nouvelles lettres d\'information.',
            'Solicitar Boletín' => 'Demander la lettre d\'information',
            'Sesión iniciada como' => 'Session démarrée en tant que',
            'Ver Borradores' => 'Voir les brouillons',
            'Ver Solicitudes' => 'Voir les demandes',
            'Boletines Disponibles' => 'Bulletins disponibles',
            'Borradores Disponibles' => 'Brouillons disponibles',
            'Buscar por título o palabra clave...' => 'Rechercher par titre ou mot-clé...',
            'Leer PDF' => 'Lire le PDF',
            'Aceptar' => 'Accepter',
            'Denegar' => 'Refuser',
            'Otras noticias' => 'Autres nouvelles',
            'Solicitudes pendientes' => 'Demandes en attente',
            'Formulario de Boletín' => 'Formulaire de bulletin',
            'Ingrese palabras clave' => 'Entrez des mots-clés',
            'Cosechas, Sistemas, Ciencia, etc..' => 'Récoltes, Systèmes, Science, etc..',
            'Ingrese una descripción de lo que su empresa busca, objetivos y criterios' => 'Entrez une description de ce que votre entreprise recherche, objectifs et critères',
            'Describa aquí lo que su empresa busca...' => 'Décrivez ici ce que votre entreprise recherche...',
            'Ingrese el rut de su empresa' => 'Entrez le numéro d\'identification de votre entreprise',
            'Enviar' => 'Envoyer',
            'SITIOS DE INTERÉS' => 'SITES D\'INTÉRÊT',
            'Ministerio de Agricultura' => 'Ministère de l\'Agriculture',
            'Licitaciones de proveedores' => 'Appels d\'offres des fournisseurs',
            'Gobierno Transparente' => 'Gouvernement Transparent',
            'Solicitudes de Transparencia' => 'Demandes de transparence',
            'Memorias FIA' => 'Rapports FIA',
            'Teléfono' => 'Téléphone',
            'REDES SOCIALES' => 'Réseaux sociaux',
            'FUNDACIÓN PARA LA INNOVACIÓN AGRARIA. Todos los derechos reservados.' => 'FONDATION POUR L\'INNOVATION AGRICOLE. Tous droits réservés.',
            'CONTACTO' => 'CONTACT',
            'Con puntos y guión' => 'Avec des points et un tiret',
        ],
    ];


    return $traducciones[$idioma][$clave] ?? $clave;
}